[package]
name = "adsb"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["json", "rustls", "cookies"] }
tokio = { version = "1", features = ["full"] }
scraper = "0.16.0"
lazy_static = "1.4.0"
calamine = { version = "0.19.1", features = ["dates"] }